### ISSUE TITLE
This is written in Java

### ISSUE THREAD

**Issue by FooSoft** [nthexwn/USGSDownloader#1]
Use Go or Python :smirk_cat:

**Comment by pashonic** [comment]
Ya, what he said^^^

**Comment by nthexwn** [comment]
*grumble*  If I had just transferred the files via thumb-drive instead of using GitHub then nobody would have to know about this dirty code...  ;-/

**Comment by FooSoft** [comment]
I just forked it so that I have a personal copy of your dirty code forever

**Comment by nthexwn** [comment]
Okay done (feel free to review, my Python is novice)!

**Comment by FooSoft** [comment]
Wow cool, you actually did it! Your python looks pretty good, although a little verbose:

```python
for mapDetailsLine in mapDetailsText:
    mapDetailsLineData = mapDetailsLine.split(" ")
    cellID = mapDetailsLineData[0]
    state = mapDetailsLineData[1]
    cellName = mapDetailsLineData[2]
    northLatitude = mapDetailsLineData[3]
    westLongitude = mapDetailsLineData[4]
    southLatitude = mapDetailsLineData[5]
    eastLongitude = mapDetailsLineData[6]
    downloadURL = mapDetailsLineData[7]
    gdaItemID = mapDetailsLineData[8]
    mapData = MapData(cellID, state, cellName, northLatitude, westLongitude, southLatitude, eastLongitude, downloadURL, gdaItemID)
    mapDataList.append(mapData)
```

to

```python
for mapDetailsLine in mapDetailsText:
    mapDataList.append(MapData(*mapDetailsLine.split()))
```

Unlike C/C++/Java Python is not a lame language so repetition is not necessary!

@nthexwn

**Comment by FooSoft** [comment]
Or even a one liner:

```python
mapDataList = map(lambda d: MapData(*d.split()), mapDetailsText)
```

**Comment by nthexwn** [comment]
Thank you for the tips.  Now I know about lambdas and argument expansion!

**Comment by FooSoft** [comment]
You should check out the `json` module. Writing files out to CSVs is for n00bs :baby:
